### ISSUE TITLE
Enforce some lints with forbid

### ISSUE THREAD

**Issue by gipsond** [ut-utp/core#113]
### what
We would like to enforce the lints listed under "steps" with `forbid`.

### steps
 - [ ] Pass the lints in each crate.
   - [ ] `bad_style`
   - [ ] `const_err`
   - [ ] `dead_code`
   - [ ] `improper_ctypes`
   - [ ] `legacy_directory_ownership`
   - [ ] `non_shorthand_field_patterns`
   - [ ] `no_mangle_generic_items`
   - [ ] `overflowing_literals`
   - [ ] `path_statements`
   - [ ] `patterns_in_fns_without_body`
   - [ ] `plugin_as_library`
   - [ ] `private_in_public`
   - [ ] `safe_extern_statics`
   - [ ] `unconditional_recursion`
   - [ ] `unused`
   - [ ] `unused_allocation`
   - [ ] `unused_lifetimes`
   - [ ] `unused_comparisons`
   - [ ] `unused_parens`
   - [ ] `while_tru`
 - [ ] Change the lint level of these lints to `forbid` in each crate.
### where
branch: N/A

### open questions
- Should we consider only enforcing some of these lints at `deny` or `warn` level?
- Should this be a milestone, with separate issues for each lint?

**Comment by rrbutani** [comment]
Closing this in favor of #170.
