### ISSUE TITLE
Rethink the interrupt interface for all the traits

### ISSUE THREAD

**Issue by rrbutani** [ut-utp/core#14]
### what
Ditch Interrupts on Adc, probably.

Input will also need to grow to have interrupts _and_ should probably grow a cache for the last character (effectively is the _KBDR_).

(Note: I _think_ none of the other interrupts need this since none of them have a 'payload' (i.e. data associated with an interrupt) but we should talk about this.)

But mainly, switch to using [AtomicBool](https://doc.rust-lang.org/core/sync/atomic/struct.AtomicBool.html)s instead of our weird double-indirection-with-functions scheme.

(Note: the atomics have interior mutability which is why we can do this without suffering.)

Our current scheme used functions because I (falsely) believed our interrupts may have payloads and I wanted to keep the interface as loose as possible for implementors since it wasn't obvious to me what implementors of the simulator side of things would want their peripherals to provide them with when an interrupt occurred. I also (incorrectly) believed there weren't concurrency primitives available in `core` (i.e. to _all_ `#![no_std]` platforms, so not things like the `Mutex` in `bare-metal`) _and_ that we'd be able to easily set interrupt handlers on the fly (the latter is a reason why passing around functions seemed appealing; implementors could potentially just set the ISR to the provided function. This was also why the functions were named `register_interrupt`. This, of course, isn't actually possible since ISRs need to be `'static`.).

Now that we've explored things a bit more, representing the interrupt flags with AtomicBools seems to be a good way to simplify the interface: it's available on `#![no_std]` and it's general enough an interface to cover the needs of instruction level simulators and, for example, data path simulators.

This would likely result in the traits with interrupts growing a function to check that an interrupt has occurred (if the traits now own the bit of shared state that is). Which leads to the question: How to work around the `'static` requirement (because of interrupt handler functions) and how should peripheral impls actually expose their state?

One way is for each peripheral _trait_ to come with a `pub static` for the state it needs. This has an big downside though:
  - You can no longer have multiple instances of a peripheral trait (regardless of whether the concrete types are the same or different)!
  - Worse yet, you (I think) won't even be warned about this; things will just not work right.

So, let's say we move the state into each peripheral trait _implementation_ (i.e. `GpioShim`, a concrete impl of `Gpio` would need to define a `pub static` for it's interrupt flags). The traits can grow a function to expose a reference to the shared state.
This is slightly better, but now the problem is that we can't have multiple instances of a particular implementation of a peripheral trait. It's also completely on implementors to make sure they're not accidentally using the same state in multiple places; we're completely forfeiting any kind of help the compiler could provide us in that area by using statics. This could definitely work, but it's not ideal.

Better yet would be if we could have instances of the implementors contain the state themselves. This completely avoids all the potential issues with using shared state in the wrong places (and we're already going to be providing a function to get references to the shared state). The problem is now `'static`: our shared state isn't guaranteed to be static.

This actually isn't a deal breaker. If we can make `'static` instances of a peripheral trait instance, we can extract a `'static` reference to the shared state.
```rust
use core::sync::atomic::{AtomicBool, Ordering};

struct Container { b: AtomicBool }

fn takes_a_static_reference(a: &'static AtomicBool) {
    println!("yay: {}", a.load(Ordering::SeqCst));
}

static C: Container = Container { b: AtomicBool::new(false) };

fn main() {
        takes_a_static_reference(&C.b);
}
```

So, this would make it so that the end user of the peripheral trait instance needs to declare it as static. In practice, the simulator _contains_ the peripheral trait instances meaning that it too would need to be static. This would require that the constructor for it (and the peripheral trait instances) would need to be const functions which is where things start to get problematic (const functions in traits aren't a thing yet).

Another problem is mutability: peripheral trait instances need to be mutable and simulators certainly need to be mutable but mutable statics are _unsafe_.

So, what do we do?

We can play the same trick we were playing with the interrupt handler functions: rather than make the entire peripheral instance static, we go and hold an (optional) static reference to the shared state inside of the interrupt handler. This ends up needing to be wrapped in a thing that allows interior mutability (Option does not) _and_ Sync meaning that we need to turn to platform specific Mutex implementations but that's okay. The problem is that we can't prove that the reference we provide (upon updating the shared state to a `Some(<reference to shared state>)` lives long enough since, of course, the reference isn't static.

So, we're back to where we started.

I think the last solution, if possible, is the best of the bunch since the `'static` stuff is really a requirement imposed by embedded platforms. It doesn't make sense to force all peripheral trait implementations everywhere to contain static state (even if they're not even capable of running on embedded platforms).

### steps
 - [x] Discuss. (This is still in the primordial stages so no real steps yet!)
 - [x] Implement
   - [x] Ditch interrupts on Adc
   - [x] Replace interrupt handler functions with AtomicBoolean flags
   - [x] Expose flags through peripheral traits
     - [x] check if interrupt occurred
     - [x] reset interrupt flag
     - [x] check if interrupts enabled
   - [x] Add way to inject static AtomicBoolean references

### where
branch: `feat-peripheral-trait-reform`

### open questions
The above about covers it for now, I think.

Wait, here's one:
  - Are the [platform restrictions on atomics](https://doc.rust-lang.org/core/sync/atomic/index.html#portability) a concern?

And another, though more of a comment:
  - Need to understand the Orderings well enough to pick them (Sequential Consistency is what we want, right?); I think these come from the C/C++11 memory model ultimately.

Also, we should talk about whether the function we add to the traits to tell whether an interrupt has occurred should account for whether interrupts are enabled or whether this should be left to the simulators.

**Comment by rrbutani** [comment]
We could have the user of the simulator (at which point the platform is _known_) provide the shared state.

This isn't a great interface and might require us to remove the Default requirement, but it _should_ work. (if we don't want to remove the Default requirement we could add functions that let you set a reference to the state.. at which point we'd have actually come full circle to `register_interrupt`)

**Comment by rrbutani** [comment]
Here's an somewhat minimal example of the last comment:

```rust
use core::marker::PhantomData;
use core::sync::atomic::{AtomicBool, Ordering};

struct Sim<'a> {
    pub perip1: Peripheral<'a>,
    pub perip2: Peripheral<'a>,
}

impl Default for Sim<'_> {
    fn default() -> Self {
        Self { perip1: Peripheral::default(), perip2: Peripheral::default() }
    }
}

impl<'a> Sim<'a> {
    fn new() -> Self {
        Self::default()
    }

    fn register_flag1(&mut self, flag: &'a AtomicBool) {
        self.perip1.register_flag(flag);
    }

    fn register_flag2(&mut self, flag: &'a AtomicBool) {
        self.perip2.register_flag(flag);
    }

    fn step(&self) {
        print!("(step)");

        if self.perip1.interrupt_occurred() { print!(" {{Interrupt 1!}}"); }
        if self.perip2.interrupt_occurred() { print!(" {{Interrupt 2!}}"); }

        println!("");
    }
}

struct Peripheral<'a> {
    flag: Option<&'a AtomicBool>,
    interrupts_enabled: bool,
}

impl Default for Peripheral<'_> {
    fn default() -> Self {
        Self { flag: None, interrupts_enabled: false }
    }
}

impl<'a> Peripheral<'a> {
    fn register_flag(&mut self, flag: &'a AtomicBool) {
        self.flag = Some(flag)
    }

    fn enable_interrupts(&mut self) {
        self.interrupts_enabled = true;
    }

    fn disable_interrupts(&mut self) {
        self.interrupts_enabled = false;
    }

    fn interrupt_occurred(&self) -> bool {
        match self.flag {
            Some(b) => {
                let occurred = b.load(Ordering::SeqCst);

                if self.interrupts_enabled && occurred {
                    b.store(false, Ordering::SeqCst);
                    true
                } else {
                    false
                }
            },
            None => unreachable!(),
        }
    }
}

// And for fun maybe we have this:
struct Set;
struct NotSet;
struct SimBuilder<'a, Flag1, Flag2>(Sim<'a>, PhantomData<Flag1>, PhantomData<Flag2>);

impl SimBuilder<'_, NotSet, NotSet> {
    pub fn new() -> Self { Self(Sim::new(), PhantomData, PhantomData) }
}

impl<'a, F2> SimBuilder<'a, NotSet, F2> {
    pub fn set_flag1(mut self, flag: &'a AtomicBool) -> SimBuilder<Set, F2> {
        self.0.register_flag1(flag);

        SimBuilder::<Set, F2>(self.0, PhantomData, PhantomData)
    }
}

impl<'a, F1> SimBuilder<'a, F1, NotSet> {
    pub fn set_flag2(mut self, flag: &'a AtomicBool) -> SimBuilder<F1, Set> {
        self.0.register_flag2(flag);

        SimBuilder::<F1, Set>(self.0, PhantomData, PhantomData)
    }
}

impl<'a> SimBuilder<'a, Set, Set> {
    pub fn build(self) -> Sim<'a> {
        self.0
    }
}

// We'd maybe want to bundle this with the peripheral impl; i.e. embedded peripheral
// impls expose wrapped types that have all this? Or something.
static GLOBAL_FLAG1: AtomicBool = AtomicBool::new(false);
static GLOBAL_FLAG2: AtomicBool = AtomicBool::new(false);

use rand::prelude::*;
use std::thread;
use std::time::Duration;

fn isr_function_1() {
    if thread_rng().gen_bool(0.1) {
        GLOBAL_FLAG1.store(true, Ordering::SeqCst);
        println!("I1");
    }
}

fn isr_function_2() {
    // Randomly trigger interrupts.
    if thread_rng().gen_bool(0.1) {
        GLOBAL_FLAG2.store(true, Ordering::SeqCst);
        println!("I2");
    }
}

fn main() {
    let isr1 = thread::spawn(|| loop {
        isr_function_1();
        thread::sleep(Duration::from_millis(500));
    });

    let isr2 = thread::spawn(|| loop {
        isr_function_2();
        thread::sleep(Duration::from_millis(500));
    });

    let mut sim = SimBuilder::new()
        .set_flag1(&GLOBAL_FLAG1)
        .set_flag2(&GLOBAL_FLAG2)
        .build();

    sim.perip1.enable_interrupts();
    sim.perip2.enable_interrupts();

    loop {
        sim.step();
        thread::sleep(Duration::from_millis(500));
    }
}
```

**Comment by gipsond** [comment]
I think we should consider somehow tying together the `Interrupt` state or `interrupts_enabled` `bool` you suggest to the `AtomicBool` so the compiler knows about the precondition that the `AtomicBool` has to be passed in before calling interrupt_occurred.

Maybe when activating interrupts, we can always require passing in a reference to the static flag you want to use?

**Comment by gipsond** [comment]
Mostly finished on `feat-peripheral-shims` but how shims handle interrupts is still fuzzy
